// Package gitx wraps the git and ssh binaries to apply and inspect identities.
package gitx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"

	"github.com/uzairrehman4/gitswitch/internal/profile"
)

// Scope selects where an identity is written.
type Scope string

const (
	Global Scope = "--global"
	Local  Scope = "--local"
)

const githubCred = "credential.https://github.com.username"

func git(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	err := cmd.Run()
	if err != nil {
		return strings.TrimSpace(out.String()), fmt.Errorf("git %s: %s", strings.Join(args, " "), strings.TrimSpace(errb.String()))
	}
	return strings.TrimSpace(out.String()), nil
}

// Get reads a config value as git would resolve it in the current directory
// (this honours includeIf folder rules). Returns "" if unset.
func Get(key string) string {
	v, _ := git("config", "--get", key)
	return v
}

// GetScoped reads a value from one scope only.
func GetScoped(s Scope, key string) string {
	v, _ := git("config", string(s), "--get", key)
	return v
}

// InRepo reports whether the working directory is inside a git work tree.
func InRepo() bool {
	v, err := git("rev-parse", "--is-inside-work-tree")
	return err == nil && v == "true"
}

// Identity is the effective identity in the current directory.
type Identity struct{ Name, Email string }

func Effective() Identity { return Identity{Get("user.name"), Get("user.email")} }
func GlobalIdentity() Identity {
	return Identity{GetScoped(Global, "user.name"), GetScoped(Global, "user.email")}
}

// slash returns a forward-slash path, which git accepts on every platform.
func slash(p string) string { return filepath.ToSlash(p) }

// SSHCommand builds the core.sshCommand that pins a key.
func SSHCommand(key string) string {
	return fmt.Sprintf(`ssh -i "%s" -o IdentitiesOnly=yes`, slash(key))
}

// Apply writes a profile into the given scope. `all` is every known profile,
// used to avoid clobbering settings that gitswitch did not write itself.
func Apply(p profile.Profile, s Scope, all []profile.Profile) error {
	if _, err := git("config", string(s), "user.name", p.GitName); err != nil {
		return err
	}
	if _, err := git("config", string(s), "user.email", p.Email); err != nil {
		return err
	}

	if p.KeyPath != "" {
		if _, err := git("config", string(s), "core.sshCommand", SSHCommand(p.KeyPath)); err != nil {
			return err
		}
	} else if s == Global && ownsSSHCommand(GetScoped(s, "core.sshCommand"), all) {
		git("config", string(s), "--unset", "core.sshCommand")
	}

	if p.GitHub != "" {
		if _, err := git("config", string(s), githubCred, p.GitHub); err != nil {
			return err
		}
	} else if s == Global && ownsGitHubUser(GetScoped(s, githubCred), all) {
		git("config", string(s), "--unset", githubCred)
	}
	return nil
}

func ownsSSHCommand(cur string, all []profile.Profile) bool {
	for _, p := range all {
		if p.KeyPath != "" && cur == SSHCommand(p.KeyPath) {
			return true
		}
	}
	return false
}

func ownsGitHubUser(cur string, all []profile.Profile) bool {
	for _, p := range all {
		if p.GitHub != "" && p.GitHub == cur {
			return true
		}
	}
	return false
}

// WriteConfigFile writes the include file used by folder rules.
func WriteConfigFile(path string, p profile.Profile) error {
	var b strings.Builder
	b.WriteString("# Generated by gitswitch. Edit with `gitswitch`, not by hand.\n")
	fmt.Fprintf(&b, "[user]\n\tname = %s\n\temail = %s\n", p.GitName, p.Email)
	if p.KeyPath != "" {
		fmt.Fprintf(&b, "[core]\n\tsshCommand = \"%s\"\n", quoteValue(SSHCommand(p.KeyPath)))
	}
	if p.GitHub != "" {
		fmt.Fprintf(&b, "[credential \"https://github.com\"]\n\tusername = %s\n", p.GitHub)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// quoteValue escapes a string for use inside a double-quoted gitconfig value.
func quoteValue(v string) string {
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(v)
}

// Link is a folder rule: repos under Dir use the profile config at File.
type Link struct{ Dir, File string }

const linkPrefix = "includeif.gitdir/i:"

func linkKey(dir string) string {
	d := slash(dir)
	if !strings.HasSuffix(d, "/") {
		d += "/"
	}
	return "includeIf.gitdir/i:" + d + ".path"
}

// LinkDir makes every repo under dir use the profile's config file.
func LinkDir(dir, configFile string) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	if st, err := os.Stat(abs); err != nil || !st.IsDir() {
		return fmt.Errorf("%s is not a directory", abs)
	}
	_, err = git("config", "--global", linkKey(abs), slash(configFile))
	return err
}

// UnlinkDir removes the folder rule for dir.
func UnlinkDir(dir string) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	_, err = git("config", "--global", "--unset", linkKey(abs))
	return err
}

// Links lists folder rules created by gitswitch (those pointing into profilesDir).
func Links(profilesDir string) []Link {
	out, err := git("config", "--global", "--get-regexp", `^includeif\..*\.path$`)
	if err != nil {
		return nil
	}
	return parseLinks(out, profilesDir)
}

func norm(p string) string {
	p = strings.ToLower(slash(p))
	return strings.TrimSuffix(p, "/")
}

func parseLinks(out, profilesDir string) []Link {
	var links []Link
	root := norm(profilesDir) + "/"
	for _, line := range strings.Split(out, "\n") {
		key, val, ok := strings.Cut(strings.TrimSpace(line), " ")
		if !ok || !strings.HasPrefix(strings.ToLower(key), linkPrefix) || !strings.HasSuffix(key, ".path") {
			continue
		}
		if !strings.HasPrefix(norm(val)+"/", root) {
			continue
		}
		dir := key[len(linkPrefix) : len(key)-len(".path")]
		links = append(links, Link{Dir: dir, File: val})
	}
	return links
}

// UnlinkProfile removes every folder rule pointing at the profile's config file.
func UnlinkProfile(profilesDir, configFile string) {
	for _, l := range Links(profilesDir) {
		if norm(l.File) == norm(configFile) {
			git("config", "--global", "--unset", "includeIf.gitdir/i:"+l.Dir+".path")
		}
	}
}

// ---- SSH ----

// DefaultKeyPath is where gitswitch generates keys.
func DefaultKeyPath(name string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".ssh", "gitswitch_"+name), nil
}

// GenerateKey creates a passphrase-less ed25519 key. It reuses an existing file.
func GenerateKey(path, comment string) (created bool, err error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return false, err
	}
	cmd := exec.Command("ssh-keygen", "-q", "-t", "ed25519", "-C", comment, "-f", path, "-N", "")
	if out, err := cmd.CombinedOutput(); err != nil {
		return false, fmt.Errorf("ssh-keygen: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return true, nil
}

// PublicKey reads the .pub file next to a private key.
func PublicKey(path string) (string, error) {
	b, err := os.ReadFile(path + ".pub")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}

var helloRe = regexp.MustCompile(`Hi ([^!]+)!`)

// TestConnection authenticates to GitHub with the profile's key and returns
// the GitHub username it resolves to.
func TestConnection(p profile.Profile) (string, error) {
	if p.KeyPath == "" {
		return "", errors.New("profile has no SSH key")
	}
	if _, err := os.Stat(p.KeyPath); err != nil {
		return "", fmt.Errorf("key not found: %s", p.KeyPath)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "ssh", "-i", p.KeyPath, "-o", "IdentitiesOnly=yes",
		"-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=accept-new", "-T", "git@github.com")
	out, _ := cmd.CombinedOutput() // GitHub exits 1 even on success
	if m := helloRe.FindStringSubmatch(string(out)); m != nil {
		return m[1], nil
	}
	if ctx.Err() != nil {
		return "", errors.New("timed out reaching github.com")
	}
	msg := strings.TrimSpace(string(out))
	if strings.Contains(msg, "Permission denied") {
		return "", errors.New("GitHub rejected this key. Add the public key at https://github.com/settings/ssh/new")
	}
	return "", fmt.Errorf("unexpected ssh output: %s", msg)
}

// CopyToClipboard is best-effort.
func CopyToClipboard(text string) bool {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		cmd = exec.Command("clip")
	case "darwin":
		cmd = exec.Command("pbcopy")
	default:
		if _, err := exec.LookPath("wl-copy"); err == nil {
			cmd = exec.Command("wl-copy")
		} else {
			cmd = exec.Command("xclip", "-selection", "clipboard")
		}
	}
	cmd.Stdin = strings.NewReader(text)
	return cmd.Run() == nil
}
