package gitx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// hookNames are the client-side hooks git runs. Setting core.hooksPath
// replaces .git/hooks entirely, so every hook gets a stub that chains to the
// repository's own hook of the same name.
var hookNames = []string{
	"applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit",
	"pre-merge-commit", "prepare-commit-msg", "commit-msg", "post-commit",
	"pre-rebase", "post-checkout", "post-merge", "pre-push", "post-rewrite",
	"pre-auto-gc", "post-index-change", "fsmonitor-watchman",
}

func hookScript(name, exe string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# Generated by gitswitch. Remove with `gitswitch guard uninstall`.\n")
	if name == "pre-commit" {
		fmt.Fprintf(&b, "\"%s\" guard check || exit 1\n", slash(exe))
	}
	// Not `git rev-parse --git-path hooks/...`: that honours core.hooksPath and
	// would resolve back to this very script, looping forever.
	fmt.Fprintf(&b, "repo_hook=\"$(git rev-parse --git-common-dir)/hooks/%s\"\n", name)
	b.WriteString("if [ -f \"$repo_hook\" ] && [ \"$repo_hook\" != \"$0\" ]; then exec \"$repo_hook\" \"$@\"; fi\nexit 0\n")
	return b.String()
}

// InstallHooks writes the hook stubs into dir.
func InstallHooks(dir, exe string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	for _, n := range hookNames {
		if err := os.WriteFile(filepath.Join(dir, n), []byte(hookScript(n, exe)), 0o755); err != nil {
			return err
		}
	}
	return nil
}

// HooksPath returns the global core.hooksPath ("" if unset).
func HooksPath() string { return GetScoped(Global, "core.hooksPath") }

// SetHooksPath points global core.hooksPath at dir.
func SetHooksPath(dir string) error {
	_, err := git("config", "--global", "core.hooksPath", slash(dir))
	return err
}

// UnsetHooksPath clears global core.hooksPath.
func UnsetHooksPath() error {
	_, err := git("config", "--global", "--unset", "core.hooksPath")
	return err
}

// SamePath compares two paths ignoring slash direction and case.
func SamePath(a, b string) bool { return norm(a) == norm(b) }

// RepoRoot returns the top-level directory of the current work tree.
func RepoRoot() (string, error) { return git("rev-parse", "--show-toplevel") }

// ExpectedFor returns the most specific folder rule that covers path.
func ExpectedFor(path string, links []Link) (Link, bool) {
	p := strings.ToLower(slash(path))
	if !strings.HasSuffix(p, "/") {
		p += "/"
	}
	var best Link
	bestLen := 0
	for _, l := range links {
		d := strings.ToLower(l.Dir)
		if !strings.HasSuffix(d, "/") {
			d += "/"
		}
		if strings.HasPrefix(p, d) && len(d) > bestLen {
			best, bestLen = l, len(d)
		}
	}
	return best, bestLen > 0
}
